name: Build and Run Receiver

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install coverage tool
      run: |
        sudo apt-get update
        sudo apt-get install -y gcovr

    - name: collect coverage
      run: gcovr --gcov-exclude=".*test.*" -r . --html --html-details -o coverage.html

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: ./*.html
        retention-days: 1
        
    - name: build for production receiver
      run: g++ -Wall -Wextra -o production ./BMSApplication_Receiver/BatteryMonitoringSystem_Receiver_Main.c 
      
    - name: production code run
      run: ./production
